  name: Integration Test Workflow

  on:
    pull_request:
      branches:
        - main

  jobs:
    connect-mysql:
      runs-on: ubuntu-latest

      env:
        DB_HOST: ${{ secrets.MYSQL_SERVER_URL }}
        DB_USER: ${{ secrets.MYSQL_USERNAME }}
        DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        DB_NAME: ${{ secrets.MYSQL_DATABASE }}
        DB_PORT: 3306

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install MySQL Server
          run: |
            sudo apt-get update
            sudo apt-get install mysql-server -y

        - name: Start MySQL Service
          run: sudo service mysql start

        - name: Set MySQL Root Password
          run: |
            mysql -u ${{secrets.MYSQL_USERNAME}} - e "ALTER USER ${{secrets.MYSQL_USERNAME}}@${{secrets.MYSQL_SERVER_URL}} IDENTIFIED BY ${{secrets.MYSQL_PASSWORD}};"
        
        - name: Exit MySQL
          run: |
            mysqladmin -u ${{secrets.MYSQL_USERNAME}} -p"${{secrets.MYSQL_PASSWORD}}" shutdown
          shell: bash

        - name: Create Database
          run: |
            mysql -u ${{ secrets.MYSQL_USERNAME }} -p"${{ secrets.MYSQL_PASSWORD }}" -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.MYSQL_DATABASE }};"

        - name: Echo Databases
          run: |
            echo "Databases in MySQL Server:"
            mysql -u ${{ secrets.MYSQL_USERNAME }} -p"${{ secrets.MYSQL_PASSWORD }}" -e "SHOW DATABASES;"

        - name: Install dependencies
          run: npm install

        - name: Connect to MySQL
          run: |
            mysql -h ${{ secrets.MYSQL_SERVER_URL }} -u ${{ secrets.MYSQL_USERNAME }} -p"${{ secrets.MYSQL_PASSWORD }}" -e "SELECT VERSION();"
          env:
            MYSQL_SERVER_URL: ${{ secrets.MYSQL_SERVER_URL }}
            MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
            MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        
        - name: Test Connection
          run: |
            npm test
            if [ $? -eq 0 ]; then
              echo "Database Connection Successful"
            else
              echo "Database Connection Failed"
              exit 1
            fi