name: Integration Test Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  setup-mysql-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL Server
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server -y

      - name: Start MySQL Service
        run: sudo service mysql start

      - name: Set up MySQL client
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"

      - name: Set up MySQL Database and User
        run: |
          mysql -h ${{ secrets.MYSQL_SERVER_URL }} -u ${{ secrets.MYSQL_USERNAME }} -p"${{ secrets.MYSQL_PASSWORD }}" -e "CREATE USER IF NOT EXISTS '${{ secrets.MYSQL_USER }}'@'%' IDENTIFIED BY '${{ secrets.MYSQL_USER_PASSWORD }}';"
          mysql -h ${{ secrets.MYSQL_SERVER_URL }} -u ${{ secrets.MYSQL_USERNAME }} -p"${{ secrets.MYSQL_PASSWORD }}" -e "GRANT ALL PRIVILEGES ON ${{ secrets.MYSQL_DATABASE }}.* TO '${{ secrets.MYSQL_USER }}'@'%';"
          mysql -h ${{ secrets.MYSQL_SERVER_URL }} -u ${{ secrets.MYSQL_USERNAME }} -p"${{ secrets.MYSQL_PASSWORD }}" -e "FLUSH PRIVILEGES;"
          mysql -h ${{ secrets.MYSQL_SERVER_URL }} -u ${{ secrets.MYSQL_USERNAME }} -p"${{ secrets.MYSQL_PASSWORD }}" -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.MYSQL_DATABASE }};"

      - name: Install dependencies
        run: npm install

      - name: Test Connection
        run: |
          npm test
          if [ $? -eq 0 ]; then
            echo "Database Connection Successful"
          else
            echo "Database Connection Failed"
            exit 1
          fi
