name: Integration Test Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  setup-mysql-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MySQL Server
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server -y

      - name: Start MySQL Service
        run: sudo service mysql start

      - name: Check secrets
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ secrets.MYSQL_USERNAME }} ${{ secrets.MYSQL_PASSWORD }} ${{ secrets.MYSQL_DATABASE }} ${{ secrets.MYSQL_SERVER_URL }}."
      # - name: Set up MySQL client
      #   uses: shogo82148/actions-setup-mysql@v1
      #   with:
      #     mysql-version: "8.0"

      - name: Set up MySQL Database and User
        run: |
          run: |
            mysql -h ${{ secrets.MYSQL_SERVER_URL }} -u ${{ secrets.MYSQL_USERNAME }} -p"${{ secrets.MYSQL_PASSWORD }}" -e "ALTER USER '${{ secrets.MYSQL_USERNAME }}'@'${{secrets.MYSQL_SERVER_URL}}' IDENTIFIED BY '${{ secrets.MYSQL_PASSWORD }}';"
            mysql -h ${{ secrets.MYSQL_SERVER_URL }} -u ${{ secrets.MYSQL_USERNAME }} -p"${{ secrets.MYSQL_PASSWORD }}" -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.MYSQL_DATABASE }};"

      - name: Install dependencies
        run: npm install

      - name: Test Connection
        run: |
          npm test
          if [ $? -eq 0 ]; then
            echo "Database Connection Successful"
          else
            echo "Database Connection Failed"
            exit 1
          fi
