  name: Integration Test Workflow

  on:
    pull_request:
      branches:
        - main

  jobs:
    connect-mysql:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up MySQL client
          uses: shogo82148/actions-setup-mysql@v1
          with:
            mysql-version: "8.0"

        - name: Set MySQL Root Password
          run: |
            mysql -u ${{ secrets.MYSQL_USERNAME }} --skip-password -e "ALTER USER ${{ secrets.MYSQL_USERNAME }}@${{ secrets.MYSQL_SERVER_URL }} IDENTIFIED BY '${{ secrets.MYSQL_PASSWORD }}';"
        
        - name: Create Database
          run: |
            mysql -u ${{ secrets.MYSQL_USERNAME }} -p"${{ secrets.MYSQL_PASSWORD }}" -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.MYSQL_DATABASE }};"

        - name: Echo Databases
          run: |
            echo "Databases in MySQL Server:"
            mysql -u ${{ secrets.MYSQL_USERNAME }} -p"${{ secrets.MYSQL_PASSWORD }}" -e "SHOW DATABASES;"

        - name: Install dependencies
          run: npm install
        - name: Test Connection
          run: |
            npm test
            if [ $? -eq 0 ]; then
              echo "Database Connection Successful"
            else
              echo "Database Connection Failed"
              exit 1
            fi