  name: Integration Test Workflow

  on:
    pull_request:
      branches:
        - main

  jobs:
    connect-mysql:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up MySQL client
          uses: shogo82148/actions-setup-mysql@v1
          with:
            mysql-version: "8.0"

        - name: Set MySQL Root Password
          run: |
            echo "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${{ secrets.MYSQL_ROOT_PASSWORD }}';" | mysql -h ${{ secrets.MYSQL_SERVER_URL }} -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}"


        - name: Install dependencies
          run: npm install
        - name: Test Connection
          run: |
            npm test
            if [ $? -eq 0 ]; then
              echo "Database Connection Successful"
            else
              echo "Database Connection Failed"
              exit 1
            fi