name: Healthz CI
on: [pull_request]

jobs:
  Run-Integration-test-for-healthz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set .env file
        run: |
          touch .env
          echo DB_USER="root" >> .env
          echo DB_PASSWORD="7758015455.Abde" >> .env
          echo DB_DATABASE="CSYE6225" >> .env
          echo DB_HOST="localhost" >> .env
          echo DB_PORT="3306" >> .env
          echo PORT="3000" >> .env
          cat .env
          ls -la

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server
          sudo service mysql start
          sudo mysql -e "CREATE USER IF NOT EXISTS '$DB_USER'@'$DB_HOST' IDENTIFIED BY '$DB_PASSWORD';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON . TO '$DB_USER'@'$DB_HOST' WITH GRANT OPTION;"
          sudo mysql -e "FLUSH PRIVILEGES;"
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;"

      - name: Install Dependencies
        run: npm install

      - name: Configure MySQL and connect
        run: |
          # Load environment variables from .env file
          source .env
          
          # Ensure the database exists and the user can connect to it
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD
          sudo mysql -e "GRANT ALL PRIVILEGES ON $DB_DATABASE.* TO '$DB_USER'@'localhost';" -u$DB_USER -p$DB_PASSWORD
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Run Integration Tests
        run: |
          # Load environment variables from .env file
          source .env
          npm test
          if [ $? -eq 0 ]; then
            echo "Build successful"
          else
            echo "Build failed"
            exit 1
          fi